name: Playwright Node
on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]
jobs:
    test:
        timeout-minutes: 60
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Test Code
              run: npm run test
            # - name: Archive output json
            #   uses: actions/upload-artifact@v3
            #   with:
            #     name: json-output
            #     path: output.json
